# Generated by Django 5.0 on 2024-10-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('matricula', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('contra', models.CharField(choices=[('SIM', 'SIM'), ('NÃO', 'NÃO')], max_length=200, verbose_name='Contra turno')),
                ('data_almoco', models.DateField()),
            ],
        ),
    ]
